### PR TITLE
fix: use graphql as a dependency to resolve TS type definition problems

### PR DESCRIPTION
**Pull request by PowerMogli**
### Summary

(If you have not already please refer to the contributing guideline as [described
here](https://github.com/feathersjs/feathers/blob/master/.github/contributing.md#pull-requests))

- [ ] Tell us about the problem your pull request is solving.
- [ ] Are there any open issues that are related to this?
- [ ] Is this PR dependent on PRs in other repos?

If so, please mention them to keep the conversations linked together.

### Other Information

If there's anything else that's important and relevant to your pull
request, mention that information here. This could include
benchmarks, or other information.

Your PR will be reviewed by a core team member and they will work with you to get your changes merged in a timely manner. If merged your PR will automatically be added to the changelog in the next release.

If your changes involve documentation updates please mention that and link the appropriate PR in [feathers-docs](https://github.com/feathersjs/feathers-docs).

Thanks for contributing to Feathers! :heart:

### CODE REVIEW

**Comment by eddyystop** [comment]
Installed!
Installing to /home/travis/.npm/_npx/4883/lib/node_modules/dtslint/typescript-installs/next...
Installed!
Error: /home/travis/build/feathers-plus/feathers-hooks-common/types/tests.ts:307:5
ERROR: 307:5  unnecessary-constructor  Remove unnecessary empty constructor.
    at /home/travis/.npm/_npx/4883/lib/node_modules/dtslint/bin/index.js:158:19
    at Generator.next (<anonymous>)
    at fulfilled (/home/travis/.npm/_npx/4883/lib/node_modules/dtslint/bin/index.js:5:58)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! feathers-hooks-common@4.19.6 lint:types: `npx dtslint types`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the feathers-hooks-common@4.19.6 lint:types script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2018-12-19T10_19_09_884Z-debug.log
npm ERR! Test failed.  See above for more details.
The command "npm test" exited with 1.
Done. Your build exited with 1.

**Comment by eddyystop** [comment]
@j2L4e ^^^

**Comment by j2L4e** [comment]
Seems unrelated. This can be merged, I'll fix the tests in #489

**Comment by j2L4e** [comment]
@PowerMogli thanks! we'll need the `@typings/graphql` package as a dependency, too

**Comment by eddyystop** [comment]
After merging PR#489 and this one, I'm getting this error locally when running `npm run test`:

```
Installed!
Error: /home/johnsz/shared/repos/feathers-plus/feathers-hooks-common/types/index.d.ts:6:35
ERROR: 6:35   expect  TypeScript@next compile error: 
Cannot find module 'libphonenumber-js'.

/home/johnsz/shared/repos/feathers-plus/feathers-hooks-common/types/tests.ts:70:35
ERROR: 70:35  expect  TypeScript@next compile error: 
Cannot find module 'libphonenumber-js'.

    at /home/johnsz/.npm/_npx/5323/lib/node_modules/dtslint/bin/index.js:158:19
    at Generator.next (<anonymous>)
    at fulfilled (/home/johnsz/.npm/_npx/5323/lib/node_modules/dtslint/bin/index.js:5:58)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! feathers-hooks-common@4.19.6 lint:types: `npx dtslint types`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the feathers-hooks-common@4.19.6 lint:types script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/johnsz/.npm/_logs/2018-12-19T14_00_30_641Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! feathers-hooks-common@4.19.6 test: `npm run lint && npm run lint:types && npm run coverage`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the feathers-hooks-common@4.19.6 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/johnsz/.npm/_logs/2018-12-19T14_00_30_775Z-debug.log
feathers-hooks-common$ 

```

**Comment by eddyystop** [comment]
@j2L4e could you submit a PR? Thanks.
